# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CreateSimpleDevice <- function() {
    invisible(.Call(`_libfreenectr_CreateSimpleDevice`))
}

SetTiltDegrees <- function(angle) {
    invisible(.Call(`_libfreenectr_SetTiltDegrees`, angle))
}

GetAccelerometers <- function() {
    .Call(`_libfreenectr_GetAccelerometers`)
}

GetTiltDegrees <- function() {
    .Call(`_libfreenectr_GetTiltDegrees`)
}

SetLed <- function(status) {
    invisible(.Call(`_libfreenectr_SetLed`, status))
}

DeviceCount <- function() {
    .Call(`_libfreenectr_DeviceCount`)
}

StartVideo <- function() {
    invisible(.Call(`_libfreenectr_StartVideo`))
}

StartDepth <- function() {
    invisible(.Call(`_libfreenectr_StartDepth`))
}

GetFrameRGB <- function() {
    .Call(`_libfreenectr_GetFrameRGB`)
}

GetFrameDepth <- function() {
    .Call(`_libfreenectr_GetFrameDepth`)
}

StartGLUTVideo <- function(RGB = TRUE, Depth = FALSE) {
    invisible(.Call(`_libfreenectr_StartGLUTVideo`, RGB, Depth))
}

GetResolution <- function() {
    .Call(`_libfreenectr_GetResolution`)
}

SetHighResolution <- function() {
    invisible(.Call(`_libfreenectr_SetHighResolution`))
}

SetMediumResolution <- function() {
    invisible(.Call(`_libfreenectr_SetMediumResolution`))
}

