# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CreateSimpleDevice <- function() {
    .Call(`_libfreenect_CreateSimpleDevice`)
}

SetTiltDegrees <- function(device, angle) {
    invisible(.Call(`_libfreenect_SetTiltDegrees`, device, angle))
}

GetAccelerometers <- function(device) {
    .Call(`_libfreenect_GetAccelerometers`, device)
}

GetTiltDegrees <- function(device) {
    .Call(`_libfreenect_GetTiltDegrees`, device)
}

SetLed <- function(device, status) {
    invisible(.Call(`_libfreenect_SetLed`, device, status))
}

